//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _23092019_dotNet2
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Product()
        {
            this.tbl_CustomerBooking = new HashSet<tbl_CustomerBooking>();
            this.tbl_CustomerBooking1 = new HashSet<tbl_CustomerBooking>();
        }
    
        public short id { get; set; }
        public string productCode { get; set; }
        public string productName { get; set; }
        public Nullable<short> productCategoryId { get; set; }
        public string productCategoryName { get; set; }
        public string urlImage { get; set; }
        public Nullable<decimal> priceOne { get; set; }
        public Nullable<decimal> priceIn { get; set; }
        public Nullable<decimal> priceOut { get; set; }
        public Nullable<short> quantity { get; set; }
        public Nullable<int> status { get; set; }
        public string supplier { get; set; }
        public Nullable<System.DateTime> importDate { get; set; }
        public Nullable<short> VAT { get; set; }
        public Nullable<System.DateTime> createdTime { get; set; }
        public Nullable<System.DateTime> updatedTime { get; set; }
        public string createdBy { get; set; }
        public string updatedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_CustomerBooking> tbl_CustomerBooking { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_CustomerBooking> tbl_CustomerBooking1 { get; set; }
        public virtual tbl_ProductCategory tbl_ProductCategory { get; set; }
    }
}
