//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _23092019_dotNet2
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CustomerBooking
    {
        public short id { get; set; }
        public Nullable<short> medicalBillId { get; set; }
        public Nullable<short> serviceUnitId { get; set; }
        public Nullable<System.DateTime> bookingDate { get; set; }
        public Nullable<System.DateTime> comingDate { get; set; }
        public Nullable<short> officeId { get; set; }
        public Nullable<short> productId { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<decimal> servicePrice { get; set; }
        public Nullable<decimal> payment { get; set; }
        public Nullable<decimal> debt { get; set; }
        public Nullable<int> payMethod { get; set; }
        public Nullable<System.DateTime> createdTime { get; set; }
        public Nullable<System.DateTime> updatedTime { get; set; }
        public string createdBy { get; set; }
        public string updatedBy { get; set; }
    
        public virtual tbl_MedicalBill tbl_MedicalBill { get; set; }
        public virtual tbl_MedicalBill tbl_MedicalBill1 { get; set; }
        public virtual tbl_Office tbl_Office { get; set; }
        public virtual tbl_Office tbl_Office1 { get; set; }
        public virtual tbl_Product tbl_Product { get; set; }
        public virtual tbl_Product tbl_Product1 { get; set; }
        public virtual tbl_ServiceUnit tbl_ServiceUnit { get; set; }
        public virtual tbl_ServiceUnit tbl_ServiceUnit1 { get; set; }
    }
}
