//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _23092019_dotNet2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Customer()
        {
            this.tbl_MedicalBill = new HashSet<tbl_MedicalBill>();
            this.tbl_MedicalBill1 = new HashSet<tbl_MedicalBill>();
            this.tbl_MedicalBill2 = new HashSet<tbl_MedicalBill>();
        }
    
        public short id { get; set; }
        public string name { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public Nullable<int> gender { get; set; }
        public string phone { get; set; }
        public string userName { get; set; }
        public Nullable<short> userId { get; set; }
        public string avatar { get; set; }
        public string facebook { get; set; }
        public Nullable<short> customerType { get; set; }
        public Nullable<short> serviceUnitId { get; set; }
        public string serviceUnitName { get; set; }
        public Nullable<short> quantity { get; set; }
        public Nullable<System.DateTime> bookingDate { get; set; }
        public Nullable<System.DateTime> comingDate { get; set; }
        public Nullable<System.DateTime> reappointmentDate { get; set; }
        public string doctor { get; set; }
        public Nullable<short> officeId { get; set; }
        public string officeName { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<System.DateTime> createdTime { get; set; }
        public Nullable<System.DateTime> updatedTime { get; set; }
        public string createdBy { get; set; }
        public string updatedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_MedicalBill> tbl_MedicalBill { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_MedicalBill> tbl_MedicalBill1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_MedicalBill> tbl_MedicalBill2 { get; set; }
        public virtual tbl_Office tbl_Office { get; set; }
        public virtual tbl_ServiceUnit tbl_ServiceUnit { get; set; }
    }
}
