//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _23092019_dotNet2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ServiceUnit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_ServiceUnit()
        {
            this.tbl_CustomerBooking = new HashSet<tbl_CustomerBooking>();
            this.tbl_CustomerBooking1 = new HashSet<tbl_CustomerBooking>();
            this.tbl_Customer = new HashSet<tbl_Customer>();
        }
    
        public short id { get; set; }
        public string name { get; set; }
        public Nullable<decimal> priceVND { get; set; }
        public Nullable<decimal> priceUSD { get; set; }
        public string note { get; set; }
        public Nullable<decimal> minPrice { get; set; }
        public Nullable<decimal> maxPrice { get; set; }
        public string picture { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<System.DateTime> createdTime { get; set; }
        public Nullable<System.DateTime> updatedTime { get; set; }
        public string createdBy { get; set; }
        public string updatedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_CustomerBooking> tbl_CustomerBooking { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_CustomerBooking> tbl_CustomerBooking1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Customer> tbl_Customer { get; set; }
    }
}
